# This notebook has the idea of explore Fifa 19 players dataset, and train data exploration with pandas

In [1]:
import pandas as pd

In [2]:
players = pd.read_csv('FIFA/FIFA19_official_data.csv')# reading the data

In [3]:
players.head(8)

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Best Overall Rating,Release Clause
0,176580,L. Suárez,31,https://cdn.sofifa.com/players/176/580/19_60.png,Uruguay,https://cdn.sofifa.com/flags/uy.png,91,91,FC Barcelona,https://cdn.sofifa.com/teams/241/light_30.png,...,45.0,38.0,27.0,25.0,31.0,33.0,37.0,ST,87.0,€164M
1,194765,A. Griezmann,27,https://cdn.sofifa.com/players/194/765/19_60.png,France,https://cdn.sofifa.com/flags/fr.png,89,89,Atlético Madrid,https://cdn.sofifa.com/teams/240/light_30.png,...,54.0,48.0,14.0,8.0,14.0,13.0,14.0,LW,87.0,€145.6M
2,177003,L. Modrić,32,https://cdn.sofifa.com/players/177/003/19_60.png,Croatia,https://cdn.sofifa.com/flags/hr.png,91,91,Real Madrid,https://cdn.sofifa.com/teams/243/light_30.png,...,76.0,73.0,13.0,9.0,7.0,14.0,9.0,CM,88.0,€137.4M
3,224334,M. Acuña,26,https://cdn.sofifa.com/players/224/334/19_60.png,Argentina,https://cdn.sofifa.com/flags/ar.png,81,81,Sporting CP,https://cdn.sofifa.com/teams/237/light_30.png,...,80.0,75.0,8.0,14.0,13.0,13.0,14.0,LM,81.0,€38M
4,192985,K. De Bruyne,27,https://cdn.sofifa.com/players/192/985/19_60.png,Belgium,https://cdn.sofifa.com/flags/be.png,91,91,Manchester City,https://cdn.sofifa.com/teams/10/light_30.png,...,58.0,51.0,15.0,13.0,5.0,10.0,13.0,CAM,89.0,€172.1M
5,178518,R. Nainggolan,30,https://cdn.sofifa.com/players/178/518/19_60.png,Belgium,https://cdn.sofifa.com/flags/be.png,85,85,Inter,https://cdn.sofifa.com/teams/44/light_30.png,...,86.0,90.0,11.0,11.0,14.0,8.0,11.0,CDM,85.0,€60.4M
6,212198,Bruno Fernandes,23,https://cdn.sofifa.com/players/212/198/19_60.png,Portugal,https://cdn.sofifa.com/flags/pt.png,85,89,Sporting CP,https://cdn.sofifa.com/teams/237/light_30.png,...,64.0,57.0,12.0,14.0,15.0,8.0,14.0,CAM,84.0,€103.8M
7,176676,Marcelo,30,https://cdn.sofifa.com/players/176/676/19_60.png,Brazil,https://cdn.sofifa.com/flags/br.png,86,86,Real Madrid,https://cdn.sofifa.com/teams/243/light_30.png,...,81.0,82.0,12.0,5.0,5.0,5.0,9.0,LM,85.0,€65.6M

## This are the features of each player in our dataset:

In [4]:
data_columns = list(players.columns)
print(data_columns)

['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special', 'Preferred Foot', 'International Reputation', 'Weak Foot', 'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position', 'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until', 'Height', 'Weight', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes', 'Best Position', 'Best Overall Rating', 'Release Clause']

In [5]:
print(players.dtypes)

ID                       int64
Name                    object
Age                      int64
Photo                   object
Nationality             object
                        ...
GKPositioning          float64
GKReflexes             float64
Best Position           object
Best Overall Rating    float64
Release Clause          object
Length: 64, dtype: object

## Inicial insights of our dataset:

In [6]:
players[['Age','Overall','Special']].describe()

                Age       Overall       Special
count  17943.000000  17943.000000  17943.000000
mean      24.702057     66.331550   1599.297665
std        4.693238      6.879566    276.606776
min       15.000000     48.000000    718.000000
25%       21.000000     62.000000   1459.000000
50%       24.000000     66.000000   1639.000000
75%       28.000000     71.000000   1790.000000
max       45.000000     94.000000   2349.000000

The oldest player is 54!!!

## Discovering what is the atributte 'Special'
#### The hypotesys is that special is the sum of some 0-99 atributes

In [7]:
## The set of features we think is related to:
list_Special_Attributes = ['Crossing', 'Finishing', 'HeadingAccuracy','ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes']

In [8]:
specials = players['Special']

In [9]:
sum_atts = players[list_Special_Attributes].sum(axis=1)

In [10]:
aux_dataframe_specials = pd.DataFrame(specials)

In [11]:
aux_dataframe_specials['sum_attributes'] = sum_atts

In [12]:
aux_dataframe_specials['special - sum'] = aux_dataframe_specials['Special']-aux_dataframe_specials['sum_attributes']

In [13]:
aux_dataframe_specials.describe()

            Special  sum_attributes  special - sum
count  17943.000000    17943.000000   17943.000000
mean    1599.297665     1658.089004     -58.791339
std      276.606776      285.611272      11.577572
min      718.000000      738.000000     -96.000000
25%     1459.000000     1511.000000     -67.000000
50%     1639.000000     1699.000000     -60.000000
75%     1790.000000     1856.000000     -52.000000
max     2349.000000     2434.000000     -12.000000

#### The result of the cell above indicates that we are adding some feature that is not relevant to the 'Special' attribute

In [14]:
special_investigation = pd.concat([aux_dataframe_specials, players[list_Special_Attributes]], axis=1)

In [15]:
special_investigation

,Special,sum_attributes,special - sum,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,2349,2434.0,-85.0,77.0,92.0,82.0,82.0,90.0,86.0,86.0,...,85.0,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0
1,2293,2382.0,-89.0,82.0,89.0,84.0,84.0,87.0,87.0,86.0,...,83.0,89.0,59.0,54.0,48.0,14.0,8.0,14.0,13.0,14.0
2,2284,2376.0,-92.0,86.0,72.0,55.0,93.0,76.0,90.0,85.0,...,82.0,92.0,68.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0
3,2281,2369.0,-88.0,87.0,66.0,63.0,78.0,68.0,87.0,87.0,...,74.0,88.0,78.0,80.0,75.0,8.0,14.0,13.0,13.0,14.0
4,2279,2369.0,-90.0,93.0,82.0,55.0,92.0,82.0,86.0,85.0,...,79.0,90.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17938,764,788.0,-24.0,12.0,9.0,13.0,20.0,5.0,9.0,12.0,...,14.0,24.0,16.0,11.0,13.0,52.0,52.0,52.0,44.0,51.0
17939,757,778.0,-21.0,14.0,9.0,10.0,15.0,5.0,5.0,10.0,...,15.0,21.0,6.0,13.0,12.0,52.0,52.0,50.0,47.0,52.0
17940,753,784.0,-31.0,12.0,6.0,12.0,23.0,5.0,6.0,12.0,...,12.0,31.0,18.0,13.0,13.0,51.0,48.0,40.0,54.0,56.0
17941,743,766.0,-23.0,11.0,8.0,10.0,23.0,6.0,9.0,10.0,...,14.0,23.0,6.0,10.0,12.0,47.0,51.0,50.0,52.0,53.0
17942,718,738.0,-20.0,10.0,7.0,11.0,19.0,7.0,10.0,13.0,...,14.0,20.0,8.0,10.0,10.0,50.0,49.0,48.0,47.0,51.0

In [16]:
special_investigation.corr()['special - sum']

Special           -0.769485
sum_attributes    -0.785761
special - sum      1.000000
Crossing          -0.592292
Finishing         -0.558895
HeadingAccuracy   -0.530811
ShortPassing      -0.708241
Volleys           -0.612645
Dribbling         -0.622212
Curve             -0.633551
FKAccuracy        -0.597987
LongPassing       -0.665373
BallControl       -0.696116
Acceleration      -0.377636
SprintSpeed       -0.380730
Agility           -0.455031
Reactions         -0.693918
Balance           -0.338333
ShotPower         -0.652164
Jumping           -0.260972
Stamina           -0.548948
Strength          -0.290362
LongShots         -0.637613
Aggression        -0.534718
Interceptions     -0.412475
Positioning       -0.603524
Vision            -0.648835
Penalties         -0.575715
Composure         -1.000000
Marking           -0.412160
StandingTackle    -0.370572
SlidingTackle     -0.336538
GKDiving           0.408608
GKHandling         0.404060
GKKicking          0.403378
GKPositioning      0.398604
GKReflexes         0.406644
Name: special - sum, dtype: float64

#### We found that the correlation between 'Composure'  and 'special - sum' = -1
##### It means that Composure shoudn't be summed with other attributes

In [17]:
list_Special_Attributes.remove('Composure')

In [18]:
specials = players['Special']
sum_atts = players[list_Special_Attributes].sum(axis=1)
aux_dataframe_specials = pd.DataFrame(specials)
aux_dataframe_specials['sum_attributes'] = sum_atts
aux_dataframe_specials['special - sum'] = aux_dataframe_specials['Special']-aux_dataframe_specials['sum_attributes']
aux_dataframe_specials

       Special  sum_attributes  special - sum
0         2349          2349.0            0.0
1         2293          2293.0            0.0
2         2284          2284.0            0.0
3         2281          2281.0            0.0
4         2279          2279.0            0.0
...        ...             ...            ...
17938      764           764.0            0.0
17939      757           757.0            0.0
17940      753           753.0            0.0
17941      743           743.0            0.0
17942      718           718.0            0.0

[17943 rows x 3 columns]

In [19]:
aux_dataframe_specials.describe()#The result is thar excluding Composure of the sum, we achieve a diference of 0

            Special  sum_attributes  special - sum
count  17943.000000    17943.000000        17943.0
mean    1599.297665     1599.297665            0.0
std      276.606776      276.606776            0.0
min      718.000000      718.000000            0.0
25%     1459.000000     1459.000000            0.0
50%     1639.000000     1639.000000            0.0
75%     1790.000000     1790.000000            0.0
max     2349.000000     2349.000000            0.0

# Conclusion:

 ###### The feature 'Special' is a sum of this attributes:
 {'Crossing', 'Finishing', 'HeadingAccuracy','ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes'}
 ###### in execption of 'Composure'